loss: cibhash
arch: cibhash
backbone: vgg16
backbone_lr_scale: 0
lr: 0.001
epochs: 60
step_size: 1
eval: 10
bs: 64
maxbs: 128
no_aug: True

loss_param:
  beta: 0.001
  temperature: 0.3
  hash_layer: 'signhash'