# runtime setting
ds: cifar10
bs: 64
lr: 0.0001
nbit: 16
# method settings
loss: hashnet
arch: dpn
backbone: alexnet
optim: adam
epochs: 100
eval: 10
# loss params
loss_param:
  alpha: 1
  beta: 1
  step_continuation: 20
