# runtime setting
ds: cifar10
bs: 64
lr: 0.0001
nbit: 16
# method settings
loss: hashnet
arch: dpn
backbone: alexnet
optim: adam
epochs: &epochs 100
eval: 10
dataset_name_suffix: _resize
db_skip_preprocess: True
test_skip_preprocess: True
# loss params
loss_param:
  alpha: 1
  beta: 1
  step_continuation: *epochs