# @package _global_

model:
  _target_: models.arch.adsh.ADSH
  backbone: ${backbone}
  nbit: 64
  nclass: ${dataset.nclass}

trainer:
  _target_: trainers.adsh.ADSHTrainer

criterion:
  _target_: models.loss.adsh.ADSHLoss
  multiclass: ${dataset.multiclass}
  gamma: 200.0

method_params:
  num_samples: 4000
  inner_epochs: 30