data_folder: data/food101
nclass: 101
multiclass: False
R: -1
norm: 2
resize: 256
crop: 224

train_dataset:
  _target_: utils.datasets.HashingDataset
  root: ${data_dir}/${dataset.data_folder}
  filename: train.txt
  transform:
    - _target_: torchvision.transforms.RandomResizedCrop
      size: ${dataset.crop}
      interpolation:
        _target_: utils.transforms.interpolation
        _args_:
          - "bicubic"
    - _target_: torchvision.transforms.RandomHorizontalFlip
    - _target_: torchvision.transforms.ToTensor
    - _target_: utils.transforms.normalize_transform
      _args_:
        - ${dataset.norm}
  target_transform:
    _target_: utils.datasets.OneHot
    nclass: ${dataset.nclass}

test_dataset:
  _target_: utils.datasets.HashingDataset
  root: ${data_dir}/${dataset.data_folder}
  filename: test.txt
  transform:
    - _target_: torchvision.transforms.Resize
      size: ${dataset.resize}
      interpolation:
        _target_: utils.transforms.interpolation
        _args_:
          - "bicubic"
    - _target_: torchvision.transforms.CenterCrop
      size: ${dataset.crop}
    - _target_: torchvision.transforms.ToTensor
    - _target_: utils.transforms.normalize_transform
      _args_:
        - ${dataset.norm}
  target_transform:
    _target_: utils.datasets.OneHot
    nclass: ${dataset.nclass}

db_dataset:
  _target_: utils.datasets.HashingDataset
  root: ${data_dir}/${dataset.data_folder}
  filename: database.txt
  transform:
    - _target_: torchvision.transforms.Resize
      size: ${dataset.resize}
      interpolation:
        _target_: utils.transforms.interpolation
        _args_:
          - "bicubic"
    - _target_: torchvision.transforms.CenterCrop
      size: ${dataset.crop}
    - _target_: torchvision.transforms.ToTensor
    - _target_: utils.transforms.normalize_transform
      _args_:
        - ${dataset.norm}
  target_transform:
    _target_: utils.datasets.OneHot
    nclass: ${dataset.nclass}